default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>

development:
  <<: *default
  database: coda_development

test:
  adapter: postgresql
  database: coda_test
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432

production:
  <<: *default
  database: coda_production
